### ISSUE TITLE
求详细的说明

### ISSUE THREAD

**Issue by zhudamao-lu** [jthmath/winapi#1]
你好，我以前一直是写服务端程序的，也看过一些winapi的代码，但是太久了。像我们这种不是做客户端的程序员，这样看觉得很难，因为我们无法和其他语言的winapi对应，比如我现在想要用你的这个项目开发一个股票行情的K线图，我就不知道要用到那些，能不能给每一个API一个详细的说明呢？当然你肯定工作也很忙，如果有时间的话可以弄一下，会有更多人感兴趣的

**Comment by jthmath** [comment]
其实，WinAPI 只有 C 语言的，微软提供了详细的文档（https://developer.microsoft.com/en-us/windows/desktop ），我的 Go 版充其量是转换了一下，函数名基本保持不变，如果不知道一个函数的作用，查看上面的地址（搜索）就行。另外，开发客户端用系统的 API 是很累的，最好用成熟的 GUI 框架（如 Qt）

**Comment by zhudamao-lu** [comment]
好的谢谢你，我是使用git的新手，请以后多多指教，那么汇编的winapi也没有的吗？ 还有我不知道github里面怎么删除以前乱弄的项目

**Comment by jthmath** [comment]
@Mosalut 汇编可以调 winapi，也有点麻烦。项目设置（settings）中有删除项目的功能。

**Comment by zhudamao-lu** [comment]
好的 谢谢你 下次多交流
